#!/bin/bash

cur_date=$(date "+DATE: %D, TIME: %T")
log_date=$(date "+%F")

mkdir test

if [[ -d "$test" ]]; then
  true 
else
  touch report 
  echo "catalog test was created successfully" >> report 
  touch test/$log_date  
fi

ping www.net_nikogo.ru || echo -e "\n\n${cur_date} error ping send " >> report

