#!/bin/bash

cur_date=$(date "+DATE: %D, TIME: %T")
log_date=$(date "+%F")

mkdir ~/test &&
{	
  touch ~/report 
  echo -e "\ncatalog test was created successfully" >> ~/report 
  touch ~/test/$log_date
}  

ping www.net_nikogo.ru || echo -e "\n${cur_date} error ping send " >> ~/report

